repos:
- repo: local
  hooks:
    - id: trufflehog
      name: TruffleHog
      description: Detect secrets in your data.
      entry: bash -c 'trufflehog git --since-commit HEAD --no-verification --fail file://.'
      language: system
      stages: ["pre-commit", "pre-push"]