name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Ruff formatting check
        uses: astral-sh/ruff-action@v1

      - name: Run Mypy
        run: poetry run mypy rekor_monitor --install-types --non-interactive

      - name: Run Pylint
        run: poetry run pylint rekor_monitor

      - name: Bandit Security Check
        run: poetry run bandit -r rekor_monitor

      - name: Run TruffleHog Secret Scan
        run: trufflehog git --since-commit HEAD --no-verification --fail file://.

      - name: Run Pytest
        run: poetry run pytest --cov=rekor_monitor --cov-report=html

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./htmlcov
